module NATS
  class JetStream
    module Manager
      def add_stream: (JetStream::API::StreamConfig, ?Hash[Symbol, untyped]) -> JetStream::API::StreamCreateResponse

      def stream_info: (String, ?Hash[Symbol, untyped]) -> JetStream::API::StreamInfo

      def update_stream: (JetStream::API::StreamConfig, ?Hash[Symbol, untyped]) -> JetStream::API::StreamCreateResponse

      def delete_stream: (String, ?Hash[Symbol, untyped]) -> bool

      def add_consumer: (String, JetStream::API::ConsumerConfig, ?Hash[Symbol, untyped]) -> JetStream::API::ConsumerInfo

      def consumer_info: (String, String, ?Hash[Symbol, untyped]) -> JetStream::API::ConsumerInfo

      def delete_consumer: (String, String, ?Hash[Symbol, untyped]) -> bool

      def find_stream_name_by_subject: (String, ?Hash[Symbol, untyped]) -> String

      def get_msg: (String, ?Hash[Symbol, untyped]) -> JetStream::API::RawStreamMsg

      def get_last_msg: (String, String, ?Hash[Symbol, untyped]) -> JetStream::API::RawStreamMsg

      def account_info: () -> Hash[Symbol, untyped]

      private

      def api_request: (String, String, ?Hash[Symbol, untyped]) -> Hash[Symbol, untyped]

      def _lift_msg_to_raw_msg: (NATS::Msg) -> JetStream::API::RawStreamMsg
    end
  end
end