#!/usr/bin/env ruby

require 'rubygems'
require 'nats/client'
  
def usage
  puts "Usage: pub.rb <subject> <msg>"; exit
end

subject, msg = ARGV
usage unless subject
msg ||= 'Hello World'

NATS.start do |n|
  n.publish(subject, msg)
  NATS.stop
end
