#!/usr/bin/env ruby

require 'rubygems'
require 'nats/client'

trap("TERM") { NATS.stop }
trap("INT")  { NATS.stop }
  
def usage
  puts "Usage: sub <subject>"; exit
end

subject = ARGV.shift
usage unless subject

NATS.on_error { |err| puts "Server Error: #{err}"; exit! }

NATS.start do |n|
  puts "Listening on [#{subject}]"
  n.subscribe(subject) { |sub, msg| puts "Received on [#{sub}] : '#{msg}'" }
end
