#!/usr/bin/env ruby

require 'rubygems'
require 'nats/client'

trap("TERM") { NATS.stop }
trap("INT")  { NATS.stop }
  
def usage
  puts "Usage: sub <subject>"; exit
end

subject = ARGV.shift
usage unless subject

NATS.start do |n|
  puts "Listening on '#{subject}'"
  n.subscribe(subject) { |sub, msg| puts "Msg Received on [#{sub}] : '#{msg}'" }
end
