module NATS
  class KeyValue
    module BucketStatus
      attr_reader bucket: String

      @nfo: JetStream::API::StreamInfo

      def initialize: (JetStream::API::StreamInfo, String) -> void

      def values: () -> Integer

      def history: () -> Integer

      def ttl: () -> Float
    end
  end
end
